export const GET_URHEILIJAT = "GET_URHEILIJAT";
export const GET_URHEILIJA = "GET_URHEILIJA";
export const ADD_URHEILIJA = "ADD_URHEILIJA";
export const DELETE_URHEILIJA = "DELETE_URHEILIJA";
export const UPDATE_URHEILIJA = "UPDATE_URHEILIJA";
